```{r}
# Load required libraries
library(lme4)    # For mixed effects models
library(simr)    # For power analysis
library(ggplot2) # For plotting
library(dplyr)   # For data manipulation
library(tidyr)   # For reshaping data
library(lmerTest)

suppressPackageStartupMessages(library(here))
source(here::here("scripts", "00_setup.R"))

if (!file.exists(cfg$out_clean_heatmap)) {
  stop("Run 01_clean_trials.R first.")
}
```

```{r}
heatmap <- readRDS(cfg$out_clean_heatmap)

eligible_ids <- heatmap %>%
  filter(!tier1_exclude_incomplete_trials) %>%
  filter(!tier1_exclude_low_phone_sdt) %>%
  distinct(participant_id) %>%
  pull(participant_id)

heatmap_filtered <- heatmap %>%
  filter(participant_id %in% eligible_ids)

heatmap_filtered$block_c <- scale(heatmap_filtered$block_num, center = TRUE, scale = FALSE)[, 1]

rt_data <- heatmap_filtered %>%
  filter(correct == 1)
```

Accuracy
```{r}
m_acc <- glmer(
  correct ~ label_condition_c*lightness_mapping_c*attention_c
  + (1 + label_condition_c + lightness_mapping_c || participant_id),
  data = heatmap_filtered,
  family = binomial("logit"),
  control = glmerControl(
    optimizer = "bobyqa",
    optCtrl = list(maxfun = 2e5)
    )
)
summary(m_acc)

m_acc_single <- glmer(
  correct ~ lightness_mapping_c*label_condition_c
  + (1 + label_condition_c + lightness_mapping_c || participant_id),
  data = heatmap_filtered %>% filter(attention=="single"),
  family = binomial("logit"),
  control = glmerControl(
    optimizer = "bobyqa",
    optCtrl = list(maxfun = 2e5)
    )
)
summary(m_acc_single)

m_acc_dual <- glmer(
  correct ~ lightness_mapping_c*label_condition_c
  + (1 + label_condition_c + lightness_mapping_c || participant_id),
  data = heatmap_filtered %>% filter(attention=="dual"),
  family = binomial("logit"),
  control = glmerControl(
    optimizer = "bobyqa",
    optCtrl = list(maxfun = 2e5)
    )
)
summary(m_acc_dual)

```

Miss rate
```{r}
m_mr <- glmer(
  unanswered ~ label_condition_c*lightness_mapping_c*attention_c +
  + (1 + label_condition_c + lightness_mapping_c | participant_id),
  data = heatmap_filtered,
  family = binomial("logit"),
  control = glmerControl(
    optimizer = "bobyqa"
    )
)
summary(m_mr)

m_mr_single <- glmer(
  unanswered ~ label_condition_c*lightness_mapping_c +
  + (1 | participant_id),
  data = heatmap_filtered %>% filter(attention=="single"),
  family = binomial("logit"),
  control = glmerControl(
    optimizer = "bobyqa"
    )
)
summary(m_mr_single)

m_mr_dual <- glmer(
  unanswered ~ label_condition_c*lightness_mapping_c +
  + (1 + label_condition_c + lightness_mapping_c || participant_id),
  data = heatmap_filtered %>% filter(attention=="dual"),
  family = binomial("logit"),
  control = glmerControl(
    optimizer = "bobyqa"
    )
)
summary(m_mr_dual)

m_mr_dual_dark <- glmer(
  unanswered ~ label_condition_c +
  + (1 + label_condition_c || participant_id),
  data = heatmap_filtered %>% filter(attention=="dual", lightness_mapping=="dark-more"),
  family = binomial("logit"),
  control = glmerControl(
    optimizer = "bobyqa"
    )
)
summary(m_mr_dual_dark)

m_mr_dual_light <- glmer(
  unanswered ~ label_condition_c +
  + (1 + label_condition_c || participant_id),
  data = heatmap_filtered %>% filter(attention=="dual", lightness_mapping=="light-more"),
  family = binomial("logit"),
  control = glmerControl(
    optimizer = "bobyqa"
    )
)
summary(m_mr_dual_light)

m_mr_dual_high <- glmer(
  unanswered ~ lightness_mapping_c +
  + (1 + lightness_mapping_c || participant_id),
  data = heatmap_filtered %>% filter(attention=="dual", label_condition=="high-more"),
  family = binomial("logit"),
  control = glmerControl(
    optimizer = "bobyqa"
    )
)
summary(m_mr_dual_high)

m_mr_dual_low <- glmer(
  unanswered ~ lightness_mapping_c +
  + (1 || participant_id),
  data = heatmap_filtered %>% filter(attention=="dual", label_condition=="low-more"),
  family = binomial("logit"),
  control = glmerControl(
    optimizer = "bobyqa"
    )
)
summary(m_mr_dual_low)
```


Response time
```{r}
m_rt <- lmer(
  duration ~ label_condition_c*lightness_mapping_c*attention_c +
    (1 + label_condition_c + lightness_mapping_c || participant_id),
  data = rt_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(m_rt)

m_rt_single <- lmer(
  duration ~ label_condition_c*lightness_mapping_c +
    (1 + label_condition_c + lightness_mapping_c || participant_id),
  data = rt_data %>% filter(attention=="single"),
  control = lmerControl(optimizer = "bobyqa")
)
summary(m_rt_single)

m_rt_dual <- lmer(
  duration ~ label_condition_c*lightness_mapping_c +
    (1 | participant_id),
  data = rt_data %>% filter(attention=="dual"),
  control = lmerControl(optimizer = "bobyqa")
)
summary(m_rt_dual)

```

Order Effects (Block)
```{r}
m_mr_block <- glmer(
  unanswered ~ label_condition_c*lightness_mapping_c*attention_c*block_c +
  + (1 + label_condition_c + lightness_mapping_c + block_c || participant_id),
  data = heatmap_filtered,
  family = binomial("logit"),
  control = glmerControl(
    optimizer = "bobyqa"
    )
)
summary(m_mr_block)

m_acc_block <- glmer(
  correct ~ label_condition_c*lightness_mapping_c*attention_c*block_c
  + (1 + label_condition_c + lightness_mapping_c + block_c || participant_id),
  data = heatmap_filtered,
  family = binomial("logit"),
  control = glmerControl(
    optimizer = "bobyqa",
    optCtrl = list(maxfun = 2e5)
    )
)
summary(m_acc_block)

m_rt_block <- lmer(
  duration ~ label_condition_c*lightness_mapping_c*attention_c*block_c +
    (1 + label_condition_c + lightness_mapping_c + block_c || participant_id),
  data = rt_data,
  control = lmerControl(optimizer = "bobyqa")
)
summary(m_rt_block)
```